login_test_prj/login_test_app/urls.py
from django.urls import path
from . import views

app_name = 'login_test_app'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('profile_create/', views.ProfileCreateView.as_view(), name="profile_create"),
    path('profile_edit/<int:pk>/', views.ProfileEditView.as_view(), name="profile_edit"),
    path('user_list', views.UserListView.as_view()),
    path('user_listA', views.UserListAView.as_view()),
    path('user_listB', views.UserListBView.as_view()),
    path('test403/', views.MyView403, name='403'),
    path('test500/', views.MyView500, name='500'),

]

login_test_prj/login_test_prj/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static  # 本Ch11.1
from django.urls import path, include

from . import settings_common, settings_dev  # 本Ch11.1
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login_test_app.urls')),
    path('accounts/', include('allauth.urls')),  # allauthデフォルトURL：本P218
    path('__debug__/', include(debug_toolbar.urls)),

]

#　開発サーバーでMEDIA_ROOT,MEDIA_URLを渡したdjango.contrib.staticfiles.urls.static関数から
#　返されたルーティングを追加する
urlpatterns +=static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

login_test_prj/login_test_app/models.py
from accounts.models import CustomUser
from django.db import models


class UserSpecies(models.Model):
    """ユーザー種族モジュール"""
    id = models.SmallIntegerField(primary_key=True, verbose_name='id')
    species = models.CharField(verbose_name='種族', max_length=5, blank=True, null=True)

    class Mata:
        verbose_name_plural = 'UserSpecies'

    def __str__(self):
        return self.species


class Profile(models.Model):
    """個人情報モデル"""

    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT, related_name='p_names')
    # on_delete: models.CASCADE(一緒に削除);models.PROTECT(保留);models.SET_NULL(nullにする);
    #            models.SET_DEFAULT(defaultにする);models.SET()(値にする);DO_NOTHING;
    names = models.CharField(verbose_name='お名前', max_length=20)
    age = models.SmallIntegerField(verbose_name='年齢', null=True)
    # species = models.CharField(verbose_name='種族', max_length=5, blank=True, null=True)
    species = models.ForeignKey(UserSpecies, verbose_name='種族', on_delete=models.SET(0), related_name='p_species')
    photo = models.ImageField(verbose_name='写真', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Mata:
        verbose_name_plural = 'Profile'

    # 　文字列でクラスを表示する
    def __str__(self):
        return self.names

login_test_prj/login_test_app/forms/forms.py
from django import forms
from django.forms import ModelForm
from django.core.mail import EmailMessage
from login_test_app.models import Profile, UserSpecies
from .forms2 import AddForm2
from django.forms import MultiWidget
import logging

logger = logging.getLogger(__name__)


class InquiryForm(forms.Form):
    # テキストボックス　と　フォームバリデーション（入力チェック）
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # col-widget
        self.fields['name'].widget.attrs['class'] = 'form-control col-15'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前を入力してください'

        self.fields['email'].widget.attrs['class'] = 'form-control col-15'

        self.fields['message'].widget.attrs['class'] = 'form-control col-15'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ　メール送信'  # メールのタイトル
        message = '送信者名： {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = 'admin@toppage.com'
        to_list = [
            'admin@toppage.com'
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()


# class AddForm(InquiryForm):
class AddForm(AddForm2):  # 他のformsからの継承
    test1 = forms.BooleanField(label='BooleanField')
    CHOICES = (('1', 'ラーメン'), ('2', 'ソウメン'), ('3', 'イケメン'))
    test2 = forms.ChoiceField(label='ChoiceField', choices=CHOICES)
    test3 = forms.TypedChoiceField(label='TypedChoiceField', coerce='int')
    # 強制的指定した型にすることができる
    test3.choices = CHOICES + (('5', 'バナナ'),)
    # 後でパラメータを追加
    test4 = forms.URLField(label='URLField')
    test5 = forms.MultipleChoiceField(label='MultipleChoiceField', choices=CHOICES)
    test6 = forms.NullBooleanField(label='NullBooleanField')
    test7 = forms.MultipleChoiceField(label='MultipleChoiceField', choices=CHOICES,
                                      widget=forms.RadioSelect(attrs={
                                          'id': 't-2048', 'class': 'form-check-input'}))


class ProfileEditForm(forms.ModelForm):
    """プロフィール作成、編集form"""
    CHOICES = UserSpecies.objects.filter(id__lt='5')
    logger.info("種族ID＜5：{}".format(CHOICES))
    """test2 = forms.ModelChoiceField(label='ChoiceField', queryset=CHOICES)
    test3 = forms.ModelMultipleChoiceField(label='CheckboxField', queryset=CHOICES,
                                           widget=forms.CheckboxSelectMultiple(attrs={'class': 'checkbox'}))
    test4 = forms.ModelMultipleChoiceField(label='radio', queryset=CHOICES,
                                           widget=forms.RadioSelect(attrs={'class': 'radio'}))
"""
    class Meta:
        model = Profile
        # exclude = ()  # created_at,updated_atは編集できないfields
        exclude = ("user", "created_at", "updated_at")

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields.values():
                field.widget.attrs['class'] = 'form-control'

login_test_prj/login_test_app/forms/forms2.py
from django import forms
from login_test_app.models import Profile


class AddForm2(forms.Form):
    test1 = forms.BooleanField(label='BooleanField2.0')
    CHOICES = (('1', 'ラーメン'), ('2', 'ソウメン'), ('3', 'イケメン'))
    test2 = forms.ChoiceField(label='ChoiceField', choices=CHOICES)


class NewForm2(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ()

login_test_prj/login_test_app/forms/forms3.py
from django import forms


class AddForm2(forms.Form):
    test1 = forms.BooleanField(label='BooleanField3.0')
    CHOICES = (('1', 'ラーメン'), ('2', 'ソウメン'), ('3', 'イケメン'))
    test2 = forms.ChoiceField(label='ChoiceField', choices=CHOICES)


class NewForm2(forms.Form):
    test1 = forms.BooleanField(label='BooleanField3.1')
    test2 = forms.BooleanField(label='BooleanField3.2')
    test3 = forms.BooleanField(label='BooleanField3.3')

login_test_prj/login_test_app/templates/base.html
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet">

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
</head>


<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'login_test_app:index' %}">TOP PAGE</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item {% block active_inquiry %}{% endblock %}">
                            <a class="nav-link" href="{% url 'login_test_app:inquiry' %}">INQUIRY</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item {% block active_profile %}{% endblock %}">
                                <a class="nav-link" href="{% url 'login_test_app:profile' %}">マイプロフィール</a>
                            </li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">ログアウト</a>
                        </li>
                        {% else %}
                        <li class="nav-item {% block active_signup %}{% endblock %}">
                            <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                        </li>
                        <li class="nav-item {% block active_login %}{% endblock %}">
                            <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block header %}{% endblock %}

        {% if messages %}
        <div class="container">
            <div class="row">
                <div class="my-div-style w-100">
                    <ul class="messages" style="list-style: none;"> <!-- メッセージの頭に「.」がつかないように -->
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}"
                            alert-dismissible fade.in
                            {% endif %}>
                            {% if message.tags == 'alert alert-danger' %}
                            <strong>{{ message }}</strong><hr>
                            <button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
                            <span aria-hidden="true">&times;</span>
                            </button>
                            {% else %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
                            <span aria-hidden="true">&times;</span>
                            </button>
                            {{ message }}
                            <!--
                            <p><a href="#" class="alert-link">{{ message }}</a></p>
                            <p>リンク文字</p>
                            -->
                            {% endif %}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        {% endif %}
        {% block contents %}{% endblock %}

        <!-- Footer -->
        <footer class="py-5 bg-black">
            <div class="container">
                <p class="m-0 text-center text-black small">Copyright &copy;Login Test 2020</p>
            </div>
        </footer>

        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    </div>
</body>
</html>

login_test_prj/login_test_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}LoginHomePage{% endblock %}

{% block header %}
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container">
            <h1 class="masthead-heading mb-0">My Login Test</h1>
            <h2 class="masthead-subheading mb-0">御機嫌よう!!</h2>
            <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5">ログイン</a>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}
{% block contents %}
<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/01.jpg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Web Login</h2>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

login_test_prj/login_test_app/templates/inquiry.html
{% extends 'base.html'%}
{% load static %}
{% block title %}お問い合わせ{% endblock %}
{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {% for field in form %}
                    <div class="form-group row">
                        <label for ="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                            <!--
                            <strong>{{ field.id_for_label }}</strong>
                            ::
                            -->
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class="col-sm-8">
                          {{ field }}
                           {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <br><br><br>
                    <button class="btn btn-primary" type="submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

login_test_prj/login_test_app/templates/profile.html
{% extends 'base.html'%}
{% load static %}
{% block title %}マイプロフィール{% endblock %}
{% block active_profile %}active{% endblock %}
{% block head %}
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
{% endblock %}
{% block contents %}
    <div class="container">
        <div class="my-div-style w-100">
            <hr>
            <div class="row">
                <div class="col-3">
                    <strong>マイプロフィール</strong>
                </div>
            </div>
            <hr>

            {% if member_list %}
            {% if member_list.photo %}
            <div class="row">
                <div class="col-3">
                    <strong>写真：</strong>
                </div>
                <div class="col-3">
                    <img src="{{ object_list.photo.url }}" width="200" height="200"/>
                </div>
            </div>
            <hr>
            {% endif %}

            <div class="row">
                <div class="col-3">
                    <strong>お名前：</strong>
                </div>
                <div class="col-9">
                {{ object_list.names }}
                </div>

                <div class="col-3">
                    <strong>ID：</strong>
                </div>
                <div class="col-9">
                {{ object_list.user }}
                </div>

                {% if object_list.age %}
                <div class="col-3">
                    <strong>年齢：</strong>
                </div>
                <div class="col-9">
                {{ object_list.age }}歳
                </div>
                {% endif %}

                {% if object_list.species %}
                <div class="col-3">
                    <strong>種族：</strong>
                </div>
                <div class="col-9">
                    {% if object_list.species %}
                    {{ object_list.species }}族
                    {% endif %}
                </div>
                {% endif %}

                <div class="col-3">
                    <strong>更新日時：</strong>
                </div>
                <div class="col-9">
                {{ object_list.updated_at }}
                </div>
                <br>
                <br>
                <a class="btn btn-primary" href="{% url 'login_test_app:profile_edit' object_list.pk %}">編集</a>
            </div>
            <hr>
             {% else %}
                <p>プロフィール：データ無し</p>
                <br>
                <a class="btn btn-primary" href="{% url 'login_test_app:profile_create' %}">作成</a>
             {% endif %}
        </div>
    </div>
{% endblock %}

login_test_prj/login_test_app/templates/profile_create.html
{% extends 'base.html'%}
{% load static %}
{% block title %}プロフィール作成{% endblock %}
{% block active_profile_show %}active{% endblock %}
{% block contents %}
    <div class="container">
        <div class="row">
            <div class="my-div-style w-100">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table">
                        {{ form.as_table }}
                    </table>
                    <button class="btn btn-primary" type="submit">作成</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

login_test_prj/login_test_app/templates/profile_edit.html
{% extends 'base.html'%}
{% load static %}
{% block title %}プロフィール編集{% endblock %}
{% block active_profile_show %}active{% endblock %}
{% block head %}{% endblock %}
{% block contents %}
    <div class="container">
        <div class="row">
            <div class="my-div-style w-100">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table">
                        {{ form.as_table }}
                    </table>
                    <button class="btn btn-primary" type="submit">更新</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

login_test_prj/login_test_app/templates/user_list.html
{% extends 'base.html'%}
{% load static %}
{% block title %}User List{% endblock %}
{% block active_profile %}active{% endblock %}
{% block head %}
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
{% endblock %}
{% block contents %}
    <div class="container">
        <div class="my-div-style w-100">
            <hr>
            <div class="row">
                <div class="col-3">
                    <strong>ユーザー　リスト</strong>
                </div>
            </div>
            <hr>

            {% if member_list %}
            <table border="1" cellpadding="5" cellspacing="0">
                <tr>
                    <th>ユーザー名</th>
                    <th>名前</th>
                    <th>年齢</th>
                    <th>種族ID</th>
                    <th>種族</th>
                    <th>更新日時</th>
                </tr>
               {% for member in member_list %}
                <tr>
                    <td>{{ member.user }}</td>
                    <td>{{ member.names }}</td>
                    <td>
                        {% if member.age %}
                            {{ member.age }}歳
                        {% else %}
                            空
                        {% endif %}
                    </td>
                    <td>{{ member.species.id }}</td>
                    <td>
                        {{ member.species }}族
                    </td>
                    <td>
                        {% if member.updated_at %}
                            {{ member.updated_at|date:"Y年n月d日l H時i分s秒" }}
                        {% else %}
                            空
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% else %}
                <p>プロフィール：データ無し</p>
            {% endif %}

            <hr>
            <!-- ページネーション -->
            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                <span aria-hidden="true">&laquo;</span>
                                <!-- << -->
                            </a>
                        </li>
                    {% endif %}
                    {% for page_num in page_obj.paginator.page_range %}
                        {% if page_obj.number == page_num %}
                            <li class="page-item active">
                                <a class="page-link" href="#">{{ page_num }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                <span aria-hidden="true">&raquo;</span>
                                <!-- >> -->
                            </a>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}

login_test_prj/login_test_app/templates/user_listA.html
{% extends 'base.html'%}
{% load static %}
{% block title %}User List{% endblock %}
{% block active_profile %}active{% endblock %}
{% block head %}
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
{% endblock %}
{% block contents %}
    <div class="container">
        <div class="my-div-style w-100">
            <hr>
            <div class="row">
                <div class="col-3">
                    <strong>ユーザー　リスト：A</strong>
                </div>
            </div>
            <hr>

            {% if member_list %}
            <table border="1" cellpadding="5" cellspacing="0">
                <tr>
                    <th>ID</th>
                    <th>ユーザー名</th>
                    <th>管理者</th>
                    <th>メールアドレス</th>
                    <th>最後ログイン</th>
                </tr>
               {% for member in member_list %}
                <tr>
                    <td>{{ member.id }}</td>
                    <td>{{ member.username }}</td>
                    <td>
                        {% if member.is_staff %}
                            管理者
                        {% else %}
                            一般会員
                        {% endif %}
                    </td>
                    <td>
                        {{ member.email }}
                    </td>
                    <td>
                        {{ member.last_login|date:"Y年n月d日l H時i分s秒" }}
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% else %}
                <p>プロフィール：データ無し</p>
            {% endif %}

            <hr>
            <!-- ページネーション -->
            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                <span aria-hidden="true">&laquo;</span>
                                <!-- << -->
                            </a>
                        </li>
                    {% endif %}
                    {% for page_num in page_obj.paginator.page_range %}
                        {% if page_obj.number == page_num %}
                            <li class="page-item active">
                                <a class="page-link" href="#">{{ page_num }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                <span aria-hidden="true">&raquo;</span>
                                <!-- >> -->
                            </a>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}

login_test_prj/login_test_app/templates/user_listB.html
{% extends 'base.html'%}
{% load static %}
{% block title %}User List{% endblock %}
{% block active_profile %}active{% endblock %}
{% block head %}
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
{% endblock %}
{% block contents %}
    <div class="container">
        <div class="my-div-style w-100">
            <hr>
            <div class="row">
                <div class="col-3">
                    <strong>ユーザー　リスト：B</strong>
                </div>
            </div>
            <hr>

            {% if member_list %}
            <table border="1" cellpadding="5" cellspacing="0">
                <tr>
                    <th>ID</th>
                    <th>ユーザー名</th>
                    <th>お名前</th>
                    <th>管理者</th>
                    <th>メールアドレス</th>
                    <th>最後ログイン</th>
                </tr>
               {% for member in member_list %}
                <tr>
                    <td>{{ member.id }}</td>
                    <td>{{ member.username }}</td>
                    <td>
                        {% for user in member.p_names.all %}
                            {% if user.names %}
                                {{ user.names }}
                            {% else %}
                                空
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {% if member.is_staff %}
                            管理者
                        {% else %}
                            一般会員
                        {% endif %}
                    </td>
                    <td>
                        {{ member.email }}
                    </td>
                    <td>
                        {{ member.last_login|date:"Y年n月d日l H時i分s秒" }}
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% else %}
                <p>プロフィール：データ無し</p>
            {% endif %}

            <hr>
            <!-- ページネーション -->
            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                <span aria-hidden="true">&laquo;</span>
                                <!-- << -->
                            </a>
                        </li>
                    {% endif %}
                    {% for page_num in page_obj.paginator.page_range %}
                        {% if page_obj.number == page_num %}
                            <li class="page-item active">
                                <a class="page-link" href="#">{{ page_num }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                <span aria-hidden="true">&raquo;</span>
                                <!-- >> -->
                            </a>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}